export const types = {
  logged: "[Contacts, Logged]",
  changeGoBack: "[Contacts, Change Go Back]",
  changeRole: "[Clients, Change role]",
  addContacts: "[Contacts, Add contacts]",
  addClients: "[Clients, Add clients]",
  setActiveContact: "[Contacts, Set contact object to activeContact]",
  setActiveTeam: "[Contacts, Set team to activeTeam]",
  setActiveFilter: "[Contacts, Set filter to activeFilter]",
  setActiveTemplate: "[Contacts, Set template to activeTemplate]",
  setUnreaded: "[Contacts, Set unreaded to activeContact]",
  updateUnreaded: "[Contacts, Update unreaded to activeContact]",
  addNote: "[Contacts, Add note to contacts]",
  addTeam: "[Contacts, Add new team]",
  addGroup: "[Contacts, Add new group]",
  addTemplate: "[Contacts, Add template to templates]",
  addMessage: "[Contacts, Add message to contacts]",
  addTeamsMessage: "[Contacts, Add message to TeamsMessages Team]",
  editGroup: "[Contacts, Edit group]",
  editNote: "[Contacts, Edit note from contacts]",
  deleteNote: "[Contacts, Delete note from contacts]",
  addMultiMessages: "[Contacts, Add a multi message to contacts]",
  addMultiTeamContacts: "[Contacts, Add a multi teams to contacts]",
  removeGroup: "[Contacts, Remove group]",
  removeMessage: "[Contacts, Remove message from contacts]",
  removeMultiTeamContacts: "[Contacts, Remove a multi teams to contacts]",
};
